### ISSUE TITLE
Tree Proxy in Agroforestry Belt Example is missing temporal and spatial data tabs

### ISSUE THREAD

**Issue by MikeDoddNZ** [APSIMInitiative/ApsimX#10832]
### What happened?

The Tree Proxy node in the Tree Belt Example Simulation appears to be missing data in the Temporal Data and Spatial data tabs. The Constants tab is populated with data.
Selecting the tree proxy node throws an error message: "Object reference not set to an instance of an object."
However, the simulation does run. 

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
This has been resolved by #10831

**Comment by MikeDoddNZ** [comment]
So should I now be seeing data in those tabs in the example, because I still can't (downloading a fresh example).
They contain important input variables for spatial sims so I need to adjust them.

**Comment by par456** [comment]
Hmmm, the agroforestry example I opened in the newest version of apsim seems to be working, can you let me know what version number your apsim has, and what file you are trying to look at and we'll see if we can replicate what you're seeing.

**Comment by MikeDoddNZ** [comment]
Good news. I just did a reinstall (7939) on a new laptop and loaded the Tree belt example and it seems to bring those tables in OK. You can close again.
