### ISSUE TITLE
Factorial trials are doubling the simulations when there are two or more managers or operations

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#3347]
Hi.
I've been setting up factorial simulations where under each factor I need to have two managers (for example one as automatic irrigation and another as climate controller) or two operations (for example one as irrigation - for specific dates- and another to cut the pasture on specific dates). When I run these simulations, I end up having more simulations than what I should. So, I guess when I have more than one manager, or more than one operations, those are used as factors, even though they are not factors. Maybe I'm setting up the simulations wrong or maybe APSIM shouldn't be considering them as factors?
I attached here a couple of screen shots. I hope it helps to explain what I'm trying to say? The first one shows how the factorial is set up. The second one shows how the simulations are being run.

Thanks

![factors in the simulation](https://user-images.githubusercontent.com/43769255/49413351-8289da80-f7d4-11e8-9d27-ac5587b9fa41.PNG)
![simulations end up using managers as factorials](https://user-images.githubusercontent.com/43769255/49413354-887fbb80-f7d4-11e8-8ec7-de753a7b3be0.PNG)

**Comment by hol353** [comment]
Are you using a fairly recent build? I made some changes that should have fixed this.

**Comment by hol430** [comment]
Have you merged your factor/experiment/JobRunner refactoring? Or are you talking about a different change?

**Comment by mpandreucci** [comment]
Yes, I've been updating it daily. I just updated it and ran them again and the same thing is still happening?

**Comment by BenAbabaei** [comment]
@mpandreucci Hi. May I ask how you created multi-level factors? In my simulations, I have locations (i.e. management and weather) and in each location I want to have different soils or levels of initial soil moisture. But it fails to run. I attach images showing how I prepared the factors. Cheers.

![image](https://user-images.githubusercontent.com/39573622/49623353-ff0cfb00-fa18-11e8-8359-24095c824f4f.png)

![image](https://user-images.githubusercontent.com/39573622/49623365-10ee9e00-fa19-11e8-9f95-475c6ef8f646.png)

**Comment by mpandreucci** [comment]
Hi Ben.
I had locations as factors. In each location I had different managers, soils and weather (you can see in the screenshot what I had under each location). Then, as a base simulation, I had a standard simulation where I had soil, weather and managers (and operations) that referred to the ones I had under each location. Then, at the factor level (like your screenshot) I had the references for the managers or operations I needed. I attached here a screenshot, I hope that helps. Let me know if it doesn't.
![github](https://user-images.githubusercontent.com/43769255/49702007-7bd9e800-fc58-11e8-9357-d589825e5752.PNG)

**Comment by BenAbabaei** [comment]
Thanks @mpandreucci. So the 'Location' factor is not directly copied on any object in the base simulation.
What I am looking to do is to have nested factors. For example, imaging you could have two different Operations under each location so APSIM would run the combination of Location and Operation for each location (and Operations are different in each location).

Thanks. Cheers.

**Comment by BenAbabaei** [comment]
@mpandreucci by the way, I think the way you had done it, you would end up with all the combinations of the factors. I did. For each location, I put all the operations, etc. under a folder which is linked to a folder in the base simulation. That way, I would only have one management for each location and not all the combinations of management components.

![image](https://user-images.githubusercontent.com/39573622/49707133-b30ac200-fc75-11e8-8aed-497cb4b8e528.png)

**Comment by mpandreucci** [comment]
I'll give that a go. Thanks

**Comment by sno036** [comment]
@hol353 @hol430  Unfortunately the solution suggested by @BenAbabaei didn't work for @mpandreucci.  And the UI is not 'listenting' to the true/false in the enabled/disabled simulations as controlled on the Experiment node (e.g. it says it is going to run 10 simulations but managed to actually run 25/10 simulations!). We can put a bunch of work into work-arounds that will end up with some messy validation simulations but just wanted to check to see if fixing this is on the active list below doing that.  Thanks, Val and Mariana

**Comment by hol430** [comment]
I think @hol353 is working on a big overhaul of the whole experiment/factor/simulation system, but it's unlikely that that branch will be merged this year.

**Comment by BenAbabaei** [comment]
@sno036 Have a look at this thread (https://github.com/APSIMInitiative/ApsimX/issues/3378) and the file I provided. That method worked for me. Of course I am still struggling to have nested factors. But it works if you only have locations and other factors that are to be applied in all locations the same way. Cheers.

**Comment by sno036** [comment]
Hi @BenAbabaei - the start/end date were applied as shown below.  Not sure if that answers your question.
![image](https://user-images.githubusercontent.com/12176269/51448747-875b1b80-1d8d-11e9-91a5-d817f9c781f8.png)

**Comment by hol430** [comment]
@mpandreucci @sno036 If you pull down the latest changes, this should be fixed. I think.

**Comment by mpandreucci** [comment]
Yup, I saw that now the output only shows the data from the simulations that are enabled. 
The experiment node still shows all the possible factorials, but I just used the enable/disable command anyway.
Thanks,
Mariana

**Comment by hol430** [comment]
Not sure why you're still seeing all factorials...are you able to upload your .apsimx file? You will need to zip it up to attach it to the github issue (or just rename it and give it a .txt file extension).

**Comment by mpandreucci** [comment]
Hi Drew. 
I've just updated everything again and its all good. Thanks a lot for that.
