### ISSUE TITLE
Simulation stops (error msg: "Stream was too long")

### ISSUE THREAD

**Issue by morelju** [APSIMInitiative/ApsimX#3663]
Hi
Simulations seem to randomly crash when running large factorial experiments (>900 simulations)
Attached is the text file that I get 
[stream_APSIMX.txt](https://github.com/APSIMInitiative/ApsimX/files/3012829/stream_APSIMX.txt)
Do you have any suggestion on how to fix it?
I am using APSIM2018.10.29.3219.

By the way, I don't know if this kind of question should arrive here or on the Apsim user's forum, so if it's not the right place, please let me know :)

**Comment by byzheng** [comment]
It might be better to update the latest version first.

**Comment by morelju** [comment]
Yes, I did that, but it also throws me an error. I guess it has to do with this JSON format?
[apsim_updated.txt](https://github.com/APSIMInitiative/ApsimX/files/3013092/apsim_updated.txt)

**Comment by hol430** [comment]
Are you able to upload your .apsimx file? Looks like you've discovered a bug in the xml to json converter.

**Comment by morelju** [comment]
Here is the simulation file.
[simulation_20190323.zip](https://github.com/APSIMInitiative/ApsimX/files/3021540/simulation_20190323.zip)

**Comment by hol430** [comment]
Interestingly, I get a different error when I attempt to open this file - it complains about an incorrectly-named cultivar parameter.

I fixed the problem and can now open the file no problems on the latest version of apsim. Can you make sure you're on the latest version, and then try and open the file: 

[simulation_20190323.zip](https://github.com/APSIMInitiative/ApsimX/files/3027421/simulation_20190323.zip)

**Comment by morelju** [comment]
It still does not work (see attached file)
Could it be a date format issue?
[error_msg.txt](https://github.com/APSIMInitiative/ApsimX/files/3027994/error_msg.txt)

**Comment by hol430** [comment]
Looks more like a number format issue - which language/regional settings do you use? Do you by any chance normally use a comma for the decimal place, or a period for the thousands separator? Regardless, #3680 should hopefully fix this problem.

I also realised I uploaded the wrong zip file yesterday, but I don't think my modifications will solve your current problem - they fix a different issue, which you will encounter once we fix this number format issue:

[updated.zip](https://github.com/APSIMInitiative/ApsimX/files/3031564/updated.zip)

**Comment by morelju** [comment]
I use the swedish settings: the decimal separator is a dot and there is no separator for thousands. Usual swedish date format is YYYY-mm-dd but I've changed it to dd/mm/YYYY

**Comment by hol430** [comment]
If you upgrade to the latest version now do you still get the same error?

**Comment by morelju** [comment]
It works! Thanks!
