### ISSUE TITLE
K curve seems to be calculated incorrectly from soil properties

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5806]
It appears that SWIM3 can create Ks(psi) curves that are incorrect.  See summary file for deeper layers.  Ks in model is > Ks in inputs.
Soil Hydraulic Conductivity
-----------------------------------------------------------------------
                         Soil Water Potential (cm)
    x       0        10       25       100     1000    15000     10^6
-----------------------------------------------------------------------
   0.0 |      100     5.26    0.944      0.1 0.000881 3.52E-08 4.85E-15
  20.0 |      100     5.26    0.944      0.1 0.000881 3.52E-08 4.85E-15
  40.0 |      100     5.26    0.944      0.1 0.000881 3.52E-08 4.85E-15
  80.0 |      100     5.26    0.944      0.1 0.000881 3.52E-08 4.85E-15
 200.0 | 2.08E+04      340     13.2    0.099 0.000442 7.14E-07 4.14E-17
 380.0 | 1.18E+11 2.48E+07 1.63E+04    0.099  2.5E-05 1.13E-06 1.64E-19
 480.0 | 8.97E+11 1.76E+08 7.93E+04    0.099 5.56E-06  9.5E-07 2.12E-18
1200.0 |      100     5.26    0.944      0.1 0.000881 3.52E-08 4.85E-15
-----------------------------------------------------------------------
See example files
[Rangu.zip](https://github.com/APSIMInitiative/ApsimX/files/5450106/Rangu.zip)

**Comment by HamishBrownPFR** [comment]
Is is using hyprops?  I implemented that for WEIRDO so if it is using the same code there could be a bug

C:\GitHubRepos\ApsimX\Models\Soils\MultiPoreWater\HydraulicProperties.cs

**Comment by par456** [comment]
When updating and using the provided apsim file, the bug is still occuring.
