### ISSUE TITLE
WEIRDO Solute Transport - Accessing the N-solute

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#5844]
I'd like to enable solute transport in WEIRDO and I attempted to port the simple solute cascading from the SoilWater model, basically updating the solute status in each soil layer by calculating the solute flux contained in the upward and downward water movements. 

A detailed rationale with changes to codes can be accessed via: 
https://github.com/Chloe0317/APSIMsims/blob/main/WEIRDOSoluteTransport.ipynb

Changed WEIRDO.cs and HourlyData.cs can be found via:
https://github.com/Chloe0317/APSIMsims

I ran into the error "Object reference not set to an instance of an object." when I tried to map the solute from the physicalThickness to WEIRDO layers (line 894 of [WEIRDO.cs](https://github.com/Chloe0317/APSIMsims/blob/main/WEIRDO.cs)). 

           MappedNH4 = Layers.MapMass(nh4.kgha, Thickness, targetThickness);

I have three questions:
1. Is it sensible to port the solute transport of SoilWater to WEIRDO this way? Could someone give me some pointers on how to best enable solute transport in WEIRDO please?
2. I think the error is because that I'm not accessing the ISolute properly. If so, how should I do it please?
3. Is it sensible to use the MapMass function for variables such as solute.kgha please?

@hol353 @hol430 @HamishBrownPFR @hut104 
Thank you very much!

**Comment by hol430** [comment]
Looks like you're accessing the solutes the right way. The problem is that the soil standardiser runs before links are resolved. The other soil components 'work' because they don't use links to locate their dependencies. I'd say this is a bug - the soil should not be standardised until after links are resolved, possibly in the StartOfSimulation event. I'll put up a PR to try this - hopefully it doesn't break anything.

**Comment by Chloe0317** [comment]
Dear Drew, 

I tried the code in the PR, unfortunately it cannot be compiled.

What I then did is to move the map solute to layers out of the MapVariables function, and put it in the OnSimulationCommencing function (line 715 of [WEIRDO.cs](https://github.com/Chloe0317/APSIMsims/blob/main/WEIRDO.cs))

            // Initialise the efficiency factor
            SoluteFlowEfficiency = MathUtilities.CreateArrayOfValues(1.0, ProfileLayers);
            SoluteFluxEfficiency = MathUtilities.CreateArrayOfValues(1.0, ProfileLayers);

            // set the solute parameters
            no3Values = Layers.MapMass(nh4.kgha, outputlayers.Thickness, Thickness);
            ureaValues = Layers.MapMass(urea.kgha, outputlayers.Thickness, Thickness);

However, I still get the nullObject error again when trying to access solute values on line 1094.

                double NO3OutFlux = no3Values[l] * MathUtilities.Divide(OutFluxCurrentLayer, SWmm[l], 0) * SoluteFluxEfficiency[l];

as when I changed it to 

                double NO3OutFlux = MathUtilities.Divide(OutFluxCurrentLayer, SWmm[l], 0) * SoluteFluxEfficiency[l];

the error pops up on the next line.

So I believe the issue is still with accessing ISolute via WEIRDO. Can you help me with this please?
Thank you very much! Really appreciated.

**Comment by hol430** [comment]
Strange that you can't compile the changed code - it works on my machine, and on the build servers. What compile error were you getting?

I've found some more problems with weirdo, related to my changes. Will let you know when I get it fixed.

**Comment by hol430** [comment]
Looks like there's 2 different problems here. The first is accessing the solutes before links are resolved. As you found, moving the solute mapping code into a different event (e.g. StartOfSimulation) is one way to work around this.

The other probelm is that the SoluteFlowEfficiency and SoluteFluxEfficiency variables aren't being initialised so they always have their default value of null. I'm not sure if they're supposed to be settable from the gui but I notice that the soil water model just sets them to 1, so I changed weirdo to do this as well and after that, your .apsimx file ran without errors (no idea if it was behaving sensibly though). I've committed my changes to a branch on my fork called bug/Weirdo.

**Comment by HamishBrownPFR** [comment]
@Chloe0317.  Sorry I haven't had a chance to review your approach yet.  putting the SoilWat solute approach in should be an adequate stop gap but does not capture the effect of bypass flow, drainage water not mixing with solute in meso pores.  I am tied up with other stuff earlier this week but will have a look at it later in the week.

**Comment by Chloe0317** [comment]
Dear Drew,

Thank you very much! Yes, it now compiles and runs successfully.

However, I'm still not sure if the link to ISolute worked please.
The MappedNO3, MappedUrea and MappedNH4 are all zeros while
SoilNitrogen.NO3, SoilNitrogen.Urea and SoilNitrogen.NH4 contain real
values, though the SoilNitrogen.Urea doesn't appear to be disseminated to
the different soil layers at all.
So I don't think WEIRDO is talking to the Solute at all and I'm completely
clueless why this is the case.

**Comment by Chloe0317** [comment]
Dear Hamish,

That's completely fine! I'm just trying to establish some sort of solute
transport mechanisms at the moment. If you could kindly give me some
pointers on what needs to be included and how when you have some spare
time, I can then find ways to incorporate them please.
Much appreciated!

**Comment by hol430** [comment]
The mapped variables (MappedNO3, ...) are 0 because the initial no3/nh4/etc are all 0. You can check this by reporting `[Soil].Initial.NO3`. I tried changing the no3 in the chemical node and the MappedNO3 was no longer 0...so it appears that weirdo is able to access the solutes correctly.

**Comment by Chloe0317** [comment]
Dear Drew,

Thank you very much! My mistake! Instead of calling the no3 etcs at the
start of the simulation, I should have done it on a daily basis.
