### ISSUE TITLE
Issue running Debian releases in headless mode after upgrading SQLite to 4.8.5

### ISSUE THREAD

**Issue by JBris** [APSIMInitiative/ApsimX#7877]
Hello

We're currently running APSIM on Ubuntu 20.04 LTS using the following Singularity recipe as a template: https://github.com/powerPlant/apsimx-srf/blob/master/Singularity.2022.09.7085.0

We are running APSIM from the terminal in headless mode (/usr/local/bin/Models)

ApsimX version 7130 is working fine. However, when we update ApsimX to version 7136, we encounter the following error message:

```
An assembly specified in the application dependencies manifest (Models.deps.json) was not found:
  package: 'System.Data.SqlClient', version: '4.8.5'
  path: 'runtimes/unix/lib/netcoreapp2.1/System.Data.SqlClient.dll'
```

We've narrowed it down to this pull request: https://github.com/APSIMInitiative/ApsimX/pull/7728

We don't encounter this issue when running APSIM in the GUI

Thank you for any help you can provide

**Comment by hol353** [comment]
I fixed an issue about ‘dependencies manifest’ on the 1st March (for Windows and perhaps Linux as well). Can you try a newer version e.g. version >= 7169?

**Comment by JBris** [comment]
Thanks @hol353,

I've tested it with version 7177 on WSL2 and Apptainer, and I still encounter the same issue

See: https://gist.github.com/JBris/9a60328399095d5a4cb4a468aca93354

**Comment by JBris** [comment]
@hol353 

I ran into another issue with version 7136 on Windows 11:

```
$ /c/Users/james/AppData/Local/Programs/APSIM2023.1.7136.0/bin/Models.exe ~/Downloads/APSIM_7136/BaseDevelopmentToTest.apsimx
Error:
  An assembly specified in the application dependencies manifest (Models.deps.json) was not found:
    package: 'Microsoft.Win32.Registry', version: '5.0.0'
    path: 'runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll'
```

However,

I can confirm that running version 7177 from the command line works fine for Windows 11.

**Comment by ric394** [comment]
As new version works I'll close this issue off.
