### ISSUE TITLE
"Failed to publish even SubscribeToEvents" error when running >360 simulations

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#8031]
### What happened?

This error started to occur after I updated my computer so there is a chance that this is an error/issue particular to my computer.

These are links to a simplified version of the APSIMX file (but still complex enough to generate the error below) and the corresponding met files:

https://csiroau-my.sharepoint.com/:u:/r/personal/pas075_csiro_au/Documents/Documents/Simulation%20Paper%20TOS/Simulation%20that%20crashes/SimplifiedSim.apsimx?csf=1&web=1&e=kbu4dx
https://csiroau-my.sharepoint.com/:f:/r/personal/pas075_csiro_au/Documents/Documents/Simulation%20Paper%20TOS/Simulation%20that%20crashes/Weather%20Files?csf=1&web=1&e=7pEY4R

When I run 2 sites (~360 sims), it runs without error, but when I add a 3rd, I get the following error:

ERROR in file: C:\Users\Pas075\OneDrive - CSIRO\Documents\Simulation Paper TOS\SDxLocAnalysis.apsimx
Simulation name: SimSow53SitePampasIW0.78
Models.Core.SimulationException
 ---> System.Exception: Failed to publish event SubscribeToEvents. Error from subscriber SubscribeToEvents.OnConnectToEvents
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, CSharpCompilationOptions options, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, Boolean isSubmission)
   at Models.Core.ScriptCompiler.CompileTextToAssembly(String code, IEnumerable`1 referencedAssemblies, String& sourceName) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\ScriptCompiler.cs:line 229
   at Models.Core.ScriptCompiler.Compile(String code, IModel model, IEnumerable`1 referencedAssemblies) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\ScriptCompiler.cs:line 81
   at Models.Functions.CSharpExpressionFunction.Compile[T](String expression, IModel relativeTo, ScriptCompiler compiler, T& function, String& errorMessages) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Functions\CSharpExpressionFunction.cs:line 72
   at Models.ExpressionReportFrequency.TryParse(String line, Report report, IEvent events, ScriptCompiler compiler) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Report\ExpressionReportFrequency.cs:line 32
   at Models.Report.SubscribeToEvents() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Report\Report.cs:line 125
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Models.Core.Events.Publish(String eventName, Object[] args) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Events.cs:line 147
   --- End of inner exception stack trace ---
   at Models.Core.Events.Publish(String eventName, Object[] args) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Events.cs:line 151
   at Models.Core.Simulation.Prepare() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 261
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Prepare() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 265
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 213

### What Operating System are you on?

Windows

**Comment by par456** [comment]
I'm not sure why that would be happening. Is it possible for you to upload a copy of your apsim file here for me to have a look?

**Comment by hrpasl** [comment]
I'm going to email it to you now. For some reason, when I tried to drag and drop the file, it didn't work. Obviously the link I put in didn't work either.

**Comment by par456** [comment]
Thanks, will have a look.

**Comment by par456** [comment]
There was a syntax error happening in the ReportforMung,

`sum of ([Soil].SoilWater.Es + [Root].WaterUptake) from [Mungbean].Sowing to [Clock].Today.Month==5&&{Clock].Today.Day==1 as MungbeanEvaporationTranspiration`

Where clock has a { instead a [ at the front of it, same thing also happened down in the reporting frequency:

`[Clock].Today.Month==5&&{Clock].Today.Day==1`

I fixed both those and Narrabri ran all the way through then. However, I find it strange that didn't cause an issue earlier, so just double check that the report is running on the first two sites as well.

**Comment by par456** [comment]
Running this with an even larger simulation shows that it's using a stupidly high amount of memory. Need to investigate further.

**Comment by hol353** [comment]
I suspect this is caused by the exceptions that are thrown by the report frequency:
```
[Clock].Today.Month == 5 && [Clock].Today.Day == 1
```
This generates a lot of exceptions in this method of EventReportFrequency:

```c#
        public static bool TryParse(string line, Report report, IEvent events)
        {
            string[] tokens = StringUtilities.SplitStringHonouringBrackets(line, " ", '[', ']');
            if (tokens.Length == 1)
            {
                new EventReportFrequency(report, events, tokens[0]);
            } 
            else if (tokens.Length > 1) 
            {
                try
                {
                    new EventReportFrequency(report, events, tokens[0]);
                }
                catch
                {   //if trying with only first token failed, try again with entire line
                    try
                    {
                        new EventReportFrequency(report, events, line);
                    }
                    catch
                    {
                        return false;
                    }
                }
            } 
            else
            {
                return false;
            }

            return true;
        }
```

It is never a good idea to use Exceptions to detect how to parse something. Objects get created unnecessarily and it runs much slower. An alternative may be to look for the presence of special characters like =<>&| etc and then assume it is an report frequency. 

This may not be the memory usage problem but it needs to be fixed anyway.

**Comment by hrpasl** [comment]
Just to clarify, does this mean that I need to change my simulation to get it to run?

**Comment by hol353** [comment]
No I don't think so. We're working on a fix to APSIM to make run correctly with your sims.

**Comment by par456** [comment]
> Just to clarify, does this mean that I need to change my simulation to get it to run?

There is a pull request currently in queue that should fix this problem for you. I was able to run through the entire simulation with that change, so once it's passed the tests, it'll be in the next version.

**Comment by hrpasl** [comment]
Still crashes my computer and produces the same errors. Did you get this to work on your computers?
